AWSTemplateFormatVersion: '2010-09-09'
Description: ECS for Template

Parameters:
  SystemName:
    Type: String
    Default: xxxx
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    Default: dev
    AllowedValues: [all, dev, stg, prod]
    ConstraintDescription: must specify all, dev, stg, or prod.
  isDisableNetworking:
    Description: Container Disable Networking.
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: must specify true or false.
  isEssential:
    Description: Container Essential.
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: must specify true or false.
  MemoryReservation:
    Description: Container MemoryReservation.
    Type: Number
  CpuNum:
    Description: CpuNum.
    Type: Number
  MemoryAmounts:
    Description: MemoryAmounts.
    Type: Number

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  # ECSLogGroup 作成
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/logs/${TaskFamilyName}

  # ECSCluster 作成
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub
        - ${SystemName}-${EnvType}-ecs-cluster
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      CapacityProviders:
        - FARGATE_SPOT
        - FARGATE
      Tags:
        - Key: Name
          Value: !Sub
            - ${SystemName}-${EnvType}-ecs-cluster
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  # ECSTaskDefinition 作成
  # Template
  ECSTaskDefinitionTemplate: # リソース名適宜変更
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - Name: TemplateContainer # Container名を指定
        DisableNetworking: !Ref isDisableNetworking
        Essential: !Ref isEssential
        Image:
          Fn::ImportValue: !Sub
            - ${SystemName}-${EnvType}-ecr-template-uri # ECRImageURIを指定
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref ECSLogGroup
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: ecs
        MemoryReservation: !Ref MemoryReservation
      Family: TemplateTask # Task名を指定
      ExecutionRoleArn:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-role-ecs-${AWS::Region}
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      NetworkMode: awsvpc
      # 不使用の場合は削除
      # Volumes:
      #   - Name: TemplateVolume # Volume名を指定
      #     Host: {}
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref CpuNum
      Memory: !Ref MemoryAmounts
      Tags:
        - Key: Name
          Value: !Sub
            - ${SystemName}-${EnvType}-ecs-def-template # 末尾タスク定義名
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
  # ↓追加ECSTaskDefinitionのResources

  # # ECSService 作成
  # ECSService:
  #   Type: AWS::ECS::Service
  #   Properties:
  #     Cluster: !Ref EcsCluster
  #     DesiredCount: !Ref EcsServiceDesiredCount
  #     LaunchType: FARGATE
  #     NetworkConfiguration:
  #       AwsvpcConfiguration:
  #         AssignPublicIp: DISABLED
  #         SecurityGroups:
  #           - Fn::ImportValue: !Sub ${ProjectName}-${Env}-sg-ecs
  #         Subnets:
  #           - Fn::ImportValue: !Sub ${ProjectName}-${Env}-subnet-private-1
  #           - Fn::ImportValue: !Sub ${ProjectName}-${Env}-subnet-private-2
  #     ServiceName: !Sub ${ProjectName}-${Env}-ecs-service
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${ProjectName}-${Env}-ecs-service
  #     TaskDefinition:
  #       Ref: EcsTaskDifinition
  #     LoadBalancers:
  #       - ContainerName: !Sub ${ProjectName}-${Env}-ecs-container
  #         ContainerPort: 80
  #         TargetGroupArn:
  #           Fn::ImportValue: !Sub ${ProjectName}-${Env}-alb-tg-arn

Outputs:
  # ECSCluster
  ECSClusterArn:
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-ecs-cluster-arn
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  # ECSTaskDefinition
  # Template
  ECSTaskDefinitionTemplateArn: # {リソース名} + 'Arn'
    Value: !Ref ECSTaskDefinitionTemplate # リソース名
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-ecs-def-template-arn # 末尾{タスク定義名} + '-arn'
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  # ↓追加ECSTaskDefinitionのOutputs