AWSTemplateFormatVersion: 2010-09-09
Description: Bastion for Template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    AllowedValues: [all, dev, stg, prod]
    ConstraintDescription: must specify all, dev, stg, or prod.
  AMIID:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  InstanceType:
    Type: String
  IsEncrypted:
    Type: String
  VolumeSize:
    Type: Number
  VolumeType:
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  # EC2インスタンスの作成
  EC2InstanceBastion:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap [AzMap, !Ref AWS::Region, 1st]
      DisableApiTermination: false
      IamInstanceProfile:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-profile-bastion-${AWS::Region}
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      ImageId: !Ref AMIID
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      Monitoring: false
      SecurityGroupIds:
        - Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-bastion-sg
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      SubnetId:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-public-subnet1
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      Tenancy: default
      EbsOptimized: false
      SourceDestCheck: true
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            Encrypted: !Ref IsEncrypted
            VolumeSize: !Ref VolumeSize
            VolumeType: !Ref VolumeType
            DeleteOnTermination: true
      HibernationOptions:
        Configured: false
      EnclaveOptions:
        Enabled: false
      Tags:
        - Key: Name
          Value: !Sub
            - ${SystemName}-${EnvType}-bastion-instance
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  # EIP作成
  EC2InstanceBastionEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref EC2InstanceBastion
      Tags:
        - Key: Name
          Value: !Sub
          - ${SystemName}-${EnvType}-bastion-eip
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

Outputs:
  EC2InstanceBastion:
    Value: !Ref EC2InstanceBastion
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-bastion-instance
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
