AWSTemplateFormatVersion: 2010-09-09
Description: CodeCommit for Template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    AllowedValues: [all, dev, stg, prod]
    ConstraintDescription: must specify all, dev, stg, or prod.

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  # CodeCommitRepository 作成
  # Template
  CodeCommitRepositoryTemplate: # リソース名適宜変更
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: Template # RepositoryName 設定
      RepositoryDescription: Template # RepositoryDescription 設定
      Tags:
        - Key: Name
          Value: !Sub
            - ${SystemName}-${EnvType}-code-commit-repo-template # 末尾RepositoryName推奨
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
  # ↓追加RepositoryのResources

Outputs:
  # Template
  CodeCommitRepositoryTemplateName: # {リソース名} + 'Name'
    Value: !GetAtt CodeCommitRepositoryTemplate.Name # {リソース名}.Name
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-code-commit-repo-template-name # RepositoryName + 'name'
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  CodeCommitRepositoryTemplateURL: # {リソース名} + 'URL'
    Value: !GetAtt CodeCommitRepositoryTemplate.CloneUrlHttp # {リソース名}.CloneUrlHttp
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-code-commit-repo-template-url # RepositoryName + 'url'
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  # ↓追加RepositoryのOutputs
