AWSTemplateFormatVersion: '2010-09-09'
Description: ECR for Template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    Default: dev
    AllowedValues: [all, dev, stg, prod]
    ConstraintDescription: must specify all, dev, stg, or prod.
  isScanOnPush:
    Description: Enable ScanOnPush.
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: must specify true or false.
  CountNumber:
    Description: LifecyclePolicy CountNumber.
    Type: Number

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  # ECRRepository 作成
  # Template
  ECRRepositoryTemplate: # リソース名適宜変更
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: template # RepositoryName設定 (大文字不可)
      ImageScanningConfiguration:
        ScanOnPush: !Ref isScanOnPush
      LifecyclePolicy:
        LifecyclePolicyText: !Sub
          - |
            {
              "rules": [
                {
                  "rulePriority": 1,
                  "description": "Delete more then ${COUNT_NUMBER} images",
                  "selection": {
                    "tagStatus": "any",
                    "countType": "imageCountMoreThan",
                    "countNumber": ${COUNT_NUMBER}
                },
                  "action": {
                    "type": "expire"
                }
                }
              ]
            }
          - {
              COUNT_NUMBER: !Ref CountNumber,
            }
      Tags:
        - Key: Name
          Value: !Sub
          - ${SystemName}-${EnvType}-ecr-template # 末尾{RepositoryName}推奨
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
  # ↓追加ECRRepositoryのResources

Outputs:
  # Template
  ECRRepository: # リソース名
    Value: !Ref ECRRepository # リソース名
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-ecr-template # 末尾{RepositoryName}推奨
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  ECRRepositoryArn: # {リソース名} + 'Arn'
    Value: !GetAtt ECRRepository.Arn # {リソース名}.Arn
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-ecr-template-arn # 末尾{RepositoryName} + '-arn'
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  ECRRepositoryRepositoryUri: # {リソース名} + 'RepositoryUri'
    Value: !GetAtt ECRRepository.RepositoryUri # {リソース名}.RepositoryUri
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-ecr-template-uri # 末尾{RepositoryName} + '-uri'
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  # ↓追加ECRRepositoryのOutputs